apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tracee
  namespace: tracee-system
spec:
  interval: 1m
  url: https://github.com/aquasecurity/tracee.git
  ref:
    tag: "v0.19.0"
