apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tracee
  namespace: tracee-system
spec:
  targetNamespace: tracee-system
  releaseName: tracee
  interval: 5m
  timeout: 10m
  chart:
    spec:
      interval: 1m
      chart: ./deploy/helm/tracee
      sourceRef:
        kind: GitRepository
        name: tracee
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  dependsOn:
    - name: istio
      namespace: bigbang
